### ISSUE TITLE
When creating new resource while not being logged user doesn't receive feedback

### ISSUE THREAD

**Issue by Garbash** [CyberCRI/KnowNodes#144]
TypeError: Cannot set property 'type' of null
    at http://www.knownodes.com/js/controllers.js:588:46
    at wrappedCallback (http://ajax.googleapis.com/ajax/libs/angularjs/1.0.5/angular.js:6780:59)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.0.5/angular.js:6817:26
    at Object.Scope.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.0.5/angular.js:7993:28)
    at Object.Scope.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.0.5/angular.js:7858:25)
    at Object.Scope.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.0.5/angular.js:8079:24)
    at HTMLDivElement.transitionEndHandler (http://www.knownodes.com/js/lib/ui-bootstrap/ui-bootstrap-0.2.0.js:1428:28)
    at HTMLDivElement.jQuery.event.dispatch (http://www.knownodes.com/js/lib/jquery-1.9.1.js:3074:9)
    at HTMLDivElement.elemData.handle (http://www.knownodes.com/js/lib/jquery-1.9.1.js:2750:28) angular.js:5687

**Comment by couzic** [comment]
Adding an interceptor on $http and popping an alert when a 401 response is
caught might do the trick

## 

Mikael Couzic

84, rue Vergniaud
75013 Paris
09 54 90 02 55
06 51 17 97 83

2013/11/28 Garbash notifications@github.com
