### ISSUE TITLE
Server crashes on GET connection

### ISSUE THREAD

**Issue by Garbash** [CyberCRI/KnowNodes#157]
When on local version: When I click open connection page

client side:

GET http://localhost:3000/users/e9d8dafb-b00f-40d4-aec2-25a6b701958d/karma  angular.js:9230 (failed)
GET http://localhost:3000/connections/7c137868-3e40-4199-b46b-b77460c90d2f/comments  angular.js:9230 (failed)
GET http://localhost:3000/connections/7c137868-3e40-4199-b46b-b77460c90d2f/triplet  (failed)

server side:

/Users/dorgarbash/WebstormProjects/Knownodes/node_modules/streamline/lib/callbacks/runtime.js:134
                throw err;
                      ^
TypeError: string is not a function
    at **propagate (/Users/dorgarbash/WebstormProjects/Knownodes/node_modules/streamline/lib/callbacks/runtime.js:124:4)
    at ___ (/Users/dorgarbash/WebstormProjects/Knownodes/node_modules/streamline/lib/callbacks/runtime.js:89:12)
    at ___ (/Users/dorgarbash/WebstormProjects/Knownodes/model/conversion/json/UserConverter.js:24:18)
    at ___ (/Users/dorgarbash/WebstormProjects/Knownodes/node_modules/streamline/lib/callbacks/runtime.js:85:13)
    at frame.active (/Users/dorgarbash/WebstormProjects/Knownodes/node_modules/streamline/lib/callbacks/runtime.js:77:14)
    at Object.__g.trampoline.flush (/Users/dorgarbash/WebstormProjects/Knownodes/node_modules/streamline/lib/callbacks/runtime.js:20:29)
    at Request._** [as _callback](/Users/dorgarbash/WebstormProjects/Knownodes/node_modules/streamline/lib/callbacks/runtime.js:93:61)
    at Request.init.self.callback (/Users/dorgarbash/WebstormProjects/Knownodes/node_modules/neo4j/node_modules/request/main.js:120:22)
    at Request.EventEmitter.emit (events.js:99:17)
    at Request.<anonymous> (/Users/dorgarbash/WebstormProjects/Knownodes/node_modules/neo4j/node_modules/request/main.js:555:16)

Process finished with exit code 1

**Comment by Garbash** [comment]
Forgot to compile... pppffff
